[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge"]
name = "freebsd"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip-audit = ">=2.9.0,<3"

[target.linux-64.dependencies]
pip = ">=25.1.1,<26"
bandit = ">=1.8.6,<2"
