[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "freebsd"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip-audit = ">=2.9.0,<3"
python = ">=3.13.7,<3.14"
max = ">=25.7.0.dev2025091915,<26"
mojo = ">=0.25.7.0.dev2025091915,<0.26"
mojo-compiler = ">=0.25.7.0.dev2025091915,<0.26"

[target.linux-64.dependencies]
pip = ">=25.2,<26"
bandit = ">=1.8.6,<2"
