name: Potatobot

on:
  schedule:
    # Runs at midnight 00:00 UTC every Friday
    # Thursday 6:00 PM CST/7:00 PM CDT
    - cron: '0 0 * * 5' 
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync-source-tree:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important: fetch all history for merge
        # persist-credentials: false # GH credentials TODO for upstream sync no PR

    - name: Set Potatobot permissions 
      run: |
        # new gh actions bot. wip
        set -euo pipefail
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config user.name  "potatobot[bot]"
        git config user.email "potatobot@users.noreply.github.com"

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/freebsd/freebsd-src.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git merge upstream/main || echo "No upstream changes to merge"

    - name: Push updates to fork
      env:
          PUSH_FORK: ${{ secrets.PAT_REPO }}
      run: |
          git remote set-url origin "https://${{ github.actor }}:${PUSH_FORK}@github.com/${{ github.repository }}.git"
          git push origin main
